<?xml version="1.0" encoding="utf-8"?><Database Name="DbFlight" Class="DbFlightDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=&quot;F:\degree 3\visual\assignment\DbFlight.mdf&quot;;Integrated Security=True;Connect Timeout=30" SettingsObjectName="assignment.My.MySettings" SettingsPropertyName="DbFlightConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cargo" Member="Cargos">
    <Type Name="Cargo">
      <Column Name="CargoID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="Conditions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_Flight_Cargo" Member="Flight_Cargos" ThisKey="CargoID" OtherKey="CargoID" Type="Flight_Cargo" />
      <Association Name="Payment_Cargo" Member="Payment" ThisKey="PaymentID" OtherKey="PaymentID" Type="Payment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CustICNo" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="CustGender" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="CustPhoneNo" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CustAddress" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CustType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MemberPassword" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Reservation" Member="Reservations" ThisKey="CustID" OtherKey="CustID" Type="Reservation" />
    </Type>
  </Table>
  <Table Name="dbo.Flight" Member="Flights">
    <Type Name="Flight">
      <Column Name="FlightID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FlightName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FlightNumber" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DepartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DepartTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Destination" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Flight_Flight_Cargo" Member="Flight_Cargos" ThisKey="FlightID" OtherKey="FlightID" Type="Flight_Cargo" />
      <Association Name="Flight_Reservation" Member="Reservations" ThisKey="FlightID" OtherKey="FlightID" Type="Reservation" />
      <Association Name="Staff_Flight" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Flight_Cargo" Member="Flight_Cargos">
    <Type Name="Flight_Cargo">
      <Column Name="FlightID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CargoID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_Flight_Cargo" Member="Cargo" ThisKey="CargoID" OtherKey="CargoID" Type="Cargo" IsForeignKey="true" />
      <Association Name="Flight_Flight_Cargo" Member="Flight" ThisKey="FlightID" OtherKey="FlightID" Type="Flight" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Luggage" Member="Luggages">
    <Type Name="Luggage">
      <Column Name="LuggageID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="Conditions" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Reservation_Luggage" Member="Reservation" ThisKey="BookID" OtherKey="BookID" Type="Reservation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="PaymentID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PaymentType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Payment_Cargo" Member="Cargos" ThisKey="PaymentID" OtherKey="PaymentID" Type="Cargo" />
      <Association Name="Reservation_Payment" Member="Reservation" ThisKey="BookID" OtherKey="BookID" Type="Reservation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="BookID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="FlightID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CustID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Reservation_Luggage" Member="Luggages" ThisKey="BookID" OtherKey="BookID" Type="Luggage" />
      <Association Name="Reservation_Payment" Member="Payments" ThisKey="BookID" OtherKey="BookID" Type="Payment" />
      <Association Name="Reservation_Seat" Member="Seats" ThisKey="BookID" OtherKey="BookID" Type="Seat" />
      <Association Name="Customer_Reservation" Member="Customer" ThisKey="CustID" OtherKey="CustID" Type="Customer" IsForeignKey="true" />
      <Association Name="Flight_Reservation" Member="Flight" ThisKey="FlightID" OtherKey="FlightID" Type="Flight" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seat" Member="Seats">
    <Type Name="Seat">
      <Column Name="SeatID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Reservation_Seat" Member="Reservation" ThisKey="BookID" OtherKey="BookID" Type="Reservation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="StaffID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StaffGender" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="StaffICNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="StaffPhoneNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="StaffAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StaffType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="StaffPassword" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Staff_Flight" Member="Flights" ThisKey="StaffID" OtherKey="StaffID" Type="Flight" />
    </Type>
  </Table>
</Database>